spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/iortho?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: rootadmin
    password: rootmeng
  liquibase:
      enabled=false:

mybatis:
  mapper-locations: classpath:mapper/*.xml